// Generated by gencpp from file tiago_move/GenerateGrasps.msg
// DO NOT EDIT!


#ifndef TIAGO_MOVE_MESSAGE_GENERATEGRASPS_H
#define TIAGO_MOVE_MESSAGE_GENERATEGRASPS_H

#include <ros/service_traits.h>


#include <tiago_move/GenerateGraspsRequest.h>
#include <tiago_move/GenerateGraspsResponse.h>


namespace tiago_move
{

struct GenerateGrasps
{

typedef GenerateGraspsRequest Request;
typedef GenerateGraspsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateGrasps
} // namespace tiago_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiago_move::GenerateGrasps > {
  static const char* value()
  {
    return "6ba1ad78917aa4c23b081fd0be1a2270";
  }

  static const char* value(const ::tiago_move::GenerateGrasps&) { return value(); }
};

template<>
struct DataType< ::tiago_move::GenerateGrasps > {
  static const char* value()
  {
    return "tiago_move/GenerateGrasps";
  }

  static const char* value(const ::tiago_move::GenerateGrasps&) { return value(); }
};


// service_traits::MD5Sum< ::tiago_move::GenerateGraspsRequest> should match
// service_traits::MD5Sum< ::tiago_move::GenerateGrasps >
template<>
struct MD5Sum< ::tiago_move::GenerateGraspsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_move::GenerateGrasps >::value();
  }
  static const char* value(const ::tiago_move::GenerateGraspsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_move::GenerateGraspsRequest> should match
// service_traits::DataType< ::tiago_move::GenerateGrasps >
template<>
struct DataType< ::tiago_move::GenerateGraspsRequest>
{
  static const char* value()
  {
    return DataType< ::tiago_move::GenerateGrasps >::value();
  }
  static const char* value(const ::tiago_move::GenerateGraspsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiago_move::GenerateGraspsResponse> should match
// service_traits::MD5Sum< ::tiago_move::GenerateGrasps >
template<>
struct MD5Sum< ::tiago_move::GenerateGraspsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_move::GenerateGrasps >::value();
  }
  static const char* value(const ::tiago_move::GenerateGraspsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_move::GenerateGraspsResponse> should match
// service_traits::DataType< ::tiago_move::GenerateGrasps >
template<>
struct DataType< ::tiago_move::GenerateGraspsResponse>
{
  static const char* value()
  {
    return DataType< ::tiago_move::GenerateGrasps >::value();
  }
  static const char* value(const ::tiago_move::GenerateGraspsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIAGO_MOVE_MESSAGE_GENERATEGRASPS_H
